/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulador;

/**
 *
 * @author aleandro
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpSincronizacionSend = new javax.swing.ButtonGroup();
        btngrpSincronizacionReceive = new javax.swing.ButtonGroup();
        btngrpAddressingDirect = new javax.swing.ButtonGroup();
        btngrpAddressingIndirect = new javax.swing.ButtonGroup();
        btngrpFormatLength = new javax.swing.ButtonGroup();
        btngrpQueueingDiscipline = new javax.swing.ButtonGroup();
        configTabs = new javax.swing.JTabbedPane();
        configTab1Panel1 = new javax.swing.JPanel();
        panelConfigSincronizacion = new javax.swing.JPanel();
        lblSincronizacion = new javax.swing.JLabel();
        panelSincronizacionReceive = new javax.swing.JPanel();
        rdbtnBSincronizacionReceiveBlocking = new javax.swing.JRadioButton();
        lblSincronizacionReceive = new javax.swing.JLabel();
        rdbtnSincronizacionReceiveNonBlocking = new javax.swing.JRadioButton();
        rdbtnSincronizacionReceiveTestForArrival = new javax.swing.JRadioButton();
        panelSincronizacionSend = new javax.swing.JPanel();
        rdbtnSincronizacionSendNonBlocking = new javax.swing.JRadioButton();
        rdbtnSincronizacionSendBlocking = new javax.swing.JRadioButton();
        lblSincronizacionSend = new javax.swing.JLabel();
        panelConfigAddressing = new javax.swing.JPanel();
        lblAddressing = new javax.swing.JLabel();
        panelAddressingIndirect = new javax.swing.JPanel();
        rdbtnAddressingIndirectStatic = new javax.swing.JRadioButton();
        lblAddressingIndirect = new javax.swing.JLabel();
        rdbtnAddressingIndirectDynamic = new javax.swing.JRadioButton();
        rdbtnAddressingIndirectOwnership = new javax.swing.JRadioButton();
        panelAddressingDirect = new javax.swing.JPanel();
        rdbtnAddressingDirectImplicit = new javax.swing.JRadioButton();
        rdbtnAddressingDirectExplicit = new javax.swing.JRadioButton();
        lblAddressingDirect = new javax.swing.JLabel();
        panelConfigSincronizacion2 = new javax.swing.JPanel();
        lblFormat = new javax.swing.JLabel();
        panelFormatLength = new javax.swing.JPanel();
        lblFormatLength = new javax.swing.JLabel();
        rdbtnFormatLengthFixed = new javax.swing.JRadioButton();
        rdbtnLengthVariable = new javax.swing.JRadioButton();
        panelFormatContent = new javax.swing.JPanel();
        lblFormatContent = new javax.swing.JLabel();
        cboFormatContent = new javax.swing.JComboBox<>();
        panelQueueingDiscipline = new javax.swing.JPanel();
        lblQueueingDiscipline = new javax.swing.JLabel();
        rdbtnQueueingDisciplineFIFO = new javax.swing.JRadioButton();
        rdbtnQueueingDisciplinePriority = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        configTab2Panel1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txfProcessName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        txfProcessName1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        configTabs.setMinimumSize(new java.awt.Dimension(82, 40));

        panelConfigSincronizacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblSincronizacion.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblSincronizacion.setText("Synchronization");

        panelSincronizacionReceive.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btngrpSincronizacionReceive.add(rdbtnBSincronizacionReceiveBlocking);
        rdbtnBSincronizacionReceiveBlocking.setText("Blocking");

        lblSincronizacionReceive.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSincronizacionReceive.setText("Receive");

        btngrpSincronizacionReceive.add(rdbtnSincronizacionReceiveNonBlocking);
        rdbtnSincronizacionReceiveNonBlocking.setText("Non-blocking");
        rdbtnSincronizacionReceiveNonBlocking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnSincronizacionReceiveNonBlockingActionPerformed(evt);
            }
        });

        btngrpSincronizacionReceive.add(rdbtnSincronizacionReceiveTestForArrival);
        rdbtnSincronizacionReceiveTestForArrival.setText("Test for arrival");
        rdbtnSincronizacionReceiveTestForArrival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnSincronizacionReceiveTestForArrivalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSincronizacionReceiveLayout = new javax.swing.GroupLayout(panelSincronizacionReceive);
        panelSincronizacionReceive.setLayout(panelSincronizacionReceiveLayout);
        panelSincronizacionReceiveLayout.setHorizontalGroup(
            panelSincronizacionReceiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSincronizacionReceiveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSincronizacionReceiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSincronizacionReceive, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtnBSincronizacionReceiveBlocking)
                    .addComponent(rdbtnSincronizacionReceiveTestForArrival)
                    .addComponent(rdbtnSincronizacionReceiveNonBlocking))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panelSincronizacionReceiveLayout.setVerticalGroup(
            panelSincronizacionReceiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSincronizacionReceiveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSincronizacionReceive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnBSincronizacionReceiveBlocking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdbtnSincronizacionReceiveNonBlocking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnSincronizacionReceiveTestForArrival)
                .addGap(12, 12, 12))
        );

        panelSincronizacionSend.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btngrpSincronizacionSend.add(rdbtnSincronizacionSendNonBlocking);
        rdbtnSincronizacionSendNonBlocking.setText("Non-blocking");
        rdbtnSincronizacionSendNonBlocking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnSincronizacionSendNonBlockingActionPerformed(evt);
            }
        });

        btngrpSincronizacionSend.add(rdbtnSincronizacionSendBlocking);
        rdbtnSincronizacionSendBlocking.setText("Blocking");

        lblSincronizacionSend.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSincronizacionSend.setText("Send");

        javax.swing.GroupLayout panelSincronizacionSendLayout = new javax.swing.GroupLayout(panelSincronizacionSend);
        panelSincronizacionSend.setLayout(panelSincronizacionSendLayout);
        panelSincronizacionSendLayout.setHorizontalGroup(
            panelSincronizacionSendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSincronizacionSendLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSincronizacionSendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnSincronizacionSendNonBlocking)
                    .addComponent(lblSincronizacionSend, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtnSincronizacionSendBlocking))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        panelSincronizacionSendLayout.setVerticalGroup(
            panelSincronizacionSendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSincronizacionSendLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSincronizacionSend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnSincronizacionSendBlocking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnSincronizacionSendNonBlocking)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelConfigSincronizacionLayout = new javax.swing.GroupLayout(panelConfigSincronizacion);
        panelConfigSincronizacion.setLayout(panelConfigSincronizacionLayout);
        panelConfigSincronizacionLayout.setHorizontalGroup(
            panelConfigSincronizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigSincronizacionLayout.createSequentialGroup()
                .addGroup(panelConfigSincronizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfigSincronizacionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelSincronizacionReceive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConfigSincronizacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelConfigSincronizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSincronizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelSincronizacionSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelConfigSincronizacionLayout.setVerticalGroup(
            panelConfigSincronizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigSincronizacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSincronizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSincronizacionSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSincronizacionReceive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelConfigAddressing.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblAddressing.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblAddressing.setText("Addressing");

        panelAddressingIndirect.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btngrpAddressingIndirect.add(rdbtnAddressingIndirectStatic);
        rdbtnAddressingIndirectStatic.setText("Static");

        lblAddressingIndirect.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblAddressingIndirect.setText("Indirect");

        btngrpAddressingIndirect.add(rdbtnAddressingIndirectDynamic);
        rdbtnAddressingIndirectDynamic.setText("Dynamic");
        rdbtnAddressingIndirectDynamic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnAddressingIndirectDynamicActionPerformed(evt);
            }
        });

        btngrpAddressingIndirect.add(rdbtnAddressingIndirectOwnership);
        rdbtnAddressingIndirectOwnership.setText("Ownership");
        rdbtnAddressingIndirectOwnership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnAddressingIndirectOwnershipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddressingIndirectLayout = new javax.swing.GroupLayout(panelAddressingIndirect);
        panelAddressingIndirect.setLayout(panelAddressingIndirectLayout);
        panelAddressingIndirectLayout.setHorizontalGroup(
            panelAddressingIndirectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddressingIndirectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddressingIndirectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddressingIndirect, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtnAddressingIndirectStatic)
                    .addComponent(rdbtnAddressingIndirectOwnership)
                    .addComponent(rdbtnAddressingIndirectDynamic))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAddressingIndirectLayout.setVerticalGroup(
            panelAddressingIndirectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddressingIndirectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddressingIndirect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnAddressingIndirectStatic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdbtnAddressingIndirectDynamic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnAddressingIndirectOwnership)
                .addGap(12, 12, 12))
        );

        panelAddressingDirect.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btngrpAddressingDirect.add(rdbtnAddressingDirectImplicit);
        rdbtnAddressingDirectImplicit.setText("Implicit");
        rdbtnAddressingDirectImplicit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnAddressingDirectImplicitActionPerformed(evt);
            }
        });

        btngrpAddressingDirect.add(rdbtnAddressingDirectExplicit);
        rdbtnAddressingDirectExplicit.setText("Explicit");

        lblAddressingDirect.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblAddressingDirect.setText("Direct: Receive");

        javax.swing.GroupLayout panelAddressingDirectLayout = new javax.swing.GroupLayout(panelAddressingDirect);
        panelAddressingDirect.setLayout(panelAddressingDirectLayout);
        panelAddressingDirectLayout.setHorizontalGroup(
            panelAddressingDirectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddressingDirectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddressingDirectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnAddressingDirectImplicit)
                    .addComponent(rdbtnAddressingDirectExplicit)
                    .addComponent(lblAddressingDirect))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelAddressingDirectLayout.setVerticalGroup(
            panelAddressingDirectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddressingDirectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddressingDirect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnAddressingDirectExplicit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnAddressingDirectImplicit)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelConfigAddressingLayout = new javax.swing.GroupLayout(panelConfigAddressing);
        panelConfigAddressing.setLayout(panelConfigAddressingLayout);
        panelConfigAddressingLayout.setHorizontalGroup(
            panelConfigAddressingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigAddressingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConfigAddressingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConfigAddressingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelAddressingDirect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelAddressingIndirect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblAddressing, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelConfigAddressingLayout.setVerticalGroup(
            panelConfigAddressingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigAddressingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddressing, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAddressingDirect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAddressingIndirect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelConfigSincronizacion2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelConfigSincronizacion2.setPreferredSize(new java.awt.Dimension(204, 294));

        lblFormat.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblFormat.setText("Format");

        panelFormatLength.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelFormatLength.setPreferredSize(new java.awt.Dimension(188, 103));

        lblFormatLength.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblFormatLength.setText("Length");

        btngrpFormatLength.add(rdbtnFormatLengthFixed);
        rdbtnFormatLengthFixed.setText("Fixed");

        btngrpFormatLength.add(rdbtnLengthVariable);
        rdbtnLengthVariable.setText("Variable");
        rdbtnLengthVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnLengthVariableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormatLengthLayout = new javax.swing.GroupLayout(panelFormatLength);
        panelFormatLength.setLayout(panelFormatLengthLayout);
        panelFormatLengthLayout.setHorizontalGroup(
            panelFormatLengthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormatLengthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormatLengthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFormatLength, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtnFormatLengthFixed)
                    .addComponent(rdbtnLengthVariable))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        panelFormatLengthLayout.setVerticalGroup(
            panelFormatLengthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormatLengthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormatLength)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnFormatLengthFixed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdbtnLengthVariable)
                .addGap(43, 43, 43))
        );

        panelFormatContent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelFormatContent.setPreferredSize(new java.awt.Dimension(188, 103));

        lblFormatContent.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblFormatContent.setText("Content");

        cboFormatContent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Text", "Audio", "Image", "Video" }));

        javax.swing.GroupLayout panelFormatContentLayout = new javax.swing.GroupLayout(panelFormatContent);
        panelFormatContent.setLayout(panelFormatContentLayout);
        panelFormatContentLayout.setHorizontalGroup(
            panelFormatContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormatContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormatContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormatContentLayout.createSequentialGroup()
                        .addComponent(lblFormatContent)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cboFormatContent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelFormatContentLayout.setVerticalGroup(
            panelFormatContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormatContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormatContent)
                .addGap(18, 18, 18)
                .addComponent(cboFormatContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelConfigSincronizacion2Layout = new javax.swing.GroupLayout(panelConfigSincronizacion2);
        panelConfigSincronizacion2.setLayout(panelConfigSincronizacion2Layout);
        panelConfigSincronizacion2Layout.setHorizontalGroup(
            panelConfigSincronizacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigSincronizacion2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConfigSincronizacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConfigSincronizacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelFormatContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelFormatLength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelConfigSincronizacion2Layout.setVerticalGroup(
            panelConfigSincronizacion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigSincronizacion2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFormatContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFormatLength, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelQueueingDiscipline.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelQueueingDiscipline.setPreferredSize(new java.awt.Dimension(204, 294));

        lblQueueingDiscipline.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblQueueingDiscipline.setText("Queueing Discipline");

        btngrpQueueingDiscipline.add(rdbtnQueueingDisciplineFIFO);
        rdbtnQueueingDisciplineFIFO.setText("FIFO");

        btngrpQueueingDiscipline.add(rdbtnQueueingDisciplinePriority);
        rdbtnQueueingDisciplinePriority.setText("Priority");
        rdbtnQueueingDisciplinePriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnQueueingDisciplinePriorityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelQueueingDisciplineLayout = new javax.swing.GroupLayout(panelQueueingDiscipline);
        panelQueueingDiscipline.setLayout(panelQueueingDisciplineLayout);
        panelQueueingDisciplineLayout.setHorizontalGroup(
            panelQueueingDisciplineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQueueingDisciplineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQueueingDiscipline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelQueueingDisciplineLayout.createSequentialGroup()
                .addGroup(panelQueueingDisciplineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnQueueingDisciplineFIFO)
                    .addComponent(rdbtnQueueingDisciplinePriority))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelQueueingDisciplineLayout.setVerticalGroup(
            panelQueueingDisciplineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQueueingDisciplineLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblQueueingDiscipline, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbtnQueueingDisciplineFIFO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnQueueingDisciplinePriority)
                .addGap(15, 15, 15))
        );

        jButton4.setText("Next");

        javax.swing.GroupLayout configTab1Panel1Layout = new javax.swing.GroupLayout(configTab1Panel1);
        configTab1Panel1.setLayout(configTab1Panel1Layout);
        configTab1Panel1Layout.setHorizontalGroup(
            configTab1Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configTab1Panel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(configTab1Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelQueueingDiscipline, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(configTab1Panel1Layout.createSequentialGroup()
                        .addComponent(panelConfigSincronizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelConfigAddressing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelConfigSincronizacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configTab1Panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        configTab1Panel1Layout.setVerticalGroup(
            configTab1Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configTab1Panel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(configTab1Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelConfigSincronizacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelConfigAddressing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelConfigSincronizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelQueueingDiscipline, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        configTabs.addTab("Parameters", configTab1Panel1);

        configTab2Panel1.setPreferredSize(new java.awt.Dimension(32767, 32767));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txfProcessName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfProcessNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Add Queue");

        jLabel4.setText("Name");

        jLabel6.setText("Max No. Messages");

        jButton2.setText("Add");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "No. Messages", "Owner"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Short.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel7.setText("Owner");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "System", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57))
                                    .addComponent(txfProcessName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txfProcessName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(296, 456));

        txfProcessName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfProcessName1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Add Process");

        jButton1.setText("Add");

        jLabel3.setText("Name");

        jLabel5.setText("Priority");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Priority"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Short.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)
                                        .addGap(120, 120, 120))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txfProcessName1))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfProcessName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton3.setText("Next");

        javax.swing.GroupLayout configTab2Panel1Layout = new javax.swing.GroupLayout(configTab2Panel1);
        configTab2Panel1.setLayout(configTab2Panel1Layout);
        configTab2Panel1Layout.setHorizontalGroup(
            configTab2Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configTab2Panel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        configTab2Panel1Layout.setVerticalGroup(
            configTab2Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configTab2Panel1Layout.createSequentialGroup()
                .addGroup(configTab2Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(configTab2Panel1Layout.createSequentialGroup()
                        .addContainerGap(507, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(configTab2Panel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(configTab2Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        configTabs.addTab("Objects", configTab2Panel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(configTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(configTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbtnSincronizacionReceiveNonBlockingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnSincronizacionReceiveNonBlockingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnSincronizacionReceiveNonBlockingActionPerformed

    private void rdbtnSincronizacionReceiveTestForArrivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnSincronizacionReceiveTestForArrivalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnSincronizacionReceiveTestForArrivalActionPerformed

    private void rdbtnSincronizacionSendNonBlockingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnSincronizacionSendNonBlockingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnSincronizacionSendNonBlockingActionPerformed

    private void rdbtnAddressingIndirectDynamicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnAddressingIndirectDynamicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnAddressingIndirectDynamicActionPerformed

    private void rdbtnAddressingIndirectOwnershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnAddressingIndirectOwnershipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnAddressingIndirectOwnershipActionPerformed

    private void rdbtnAddressingDirectImplicitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnAddressingDirectImplicitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnAddressingDirectImplicitActionPerformed

    private void rdbtnLengthVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnLengthVariableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnLengthVariableActionPerformed

    private void rdbtnQueueingDisciplinePriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnQueueingDisciplinePriorityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnQueueingDisciplinePriorityActionPerformed

    private void txfProcessNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfProcessNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfProcessNameActionPerformed

    private void txfProcessName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfProcessName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfProcessName1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngrpAddressingDirect;
    private javax.swing.ButtonGroup btngrpAddressingIndirect;
    private javax.swing.ButtonGroup btngrpFormatLength;
    private javax.swing.ButtonGroup btngrpQueueingDiscipline;
    private javax.swing.ButtonGroup btngrpSincronizacionReceive;
    private javax.swing.ButtonGroup btngrpSincronizacionSend;
    private javax.swing.JComboBox<String> cboFormatContent;
    private javax.swing.JPanel configTab1Panel1;
    private javax.swing.JPanel configTab2Panel1;
    private javax.swing.JTabbedPane configTabs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblAddressing;
    private javax.swing.JLabel lblAddressingDirect;
    private javax.swing.JLabel lblAddressingIndirect;
    private javax.swing.JLabel lblFormat;
    private javax.swing.JLabel lblFormatContent;
    private javax.swing.JLabel lblFormatLength;
    private javax.swing.JLabel lblQueueingDiscipline;
    private javax.swing.JLabel lblSincronizacion;
    private javax.swing.JLabel lblSincronizacionReceive;
    private javax.swing.JLabel lblSincronizacionSend;
    private javax.swing.JPanel panelAddressingDirect;
    private javax.swing.JPanel panelAddressingIndirect;
    private javax.swing.JPanel panelConfigAddressing;
    private javax.swing.JPanel panelConfigSincronizacion;
    private javax.swing.JPanel panelConfigSincronizacion2;
    private javax.swing.JPanel panelFormatContent;
    private javax.swing.JPanel panelFormatLength;
    private javax.swing.JPanel panelQueueingDiscipline;
    private javax.swing.JPanel panelSincronizacionReceive;
    private javax.swing.JPanel panelSincronizacionSend;
    private javax.swing.JRadioButton rdbtnAddressingDirectExplicit;
    private javax.swing.JRadioButton rdbtnAddressingDirectImplicit;
    private javax.swing.JRadioButton rdbtnAddressingIndirectDynamic;
    private javax.swing.JRadioButton rdbtnAddressingIndirectOwnership;
    private javax.swing.JRadioButton rdbtnAddressingIndirectStatic;
    private javax.swing.JRadioButton rdbtnBSincronizacionReceiveBlocking;
    private javax.swing.JRadioButton rdbtnFormatLengthFixed;
    private javax.swing.JRadioButton rdbtnLengthVariable;
    private javax.swing.JRadioButton rdbtnQueueingDisciplineFIFO;
    private javax.swing.JRadioButton rdbtnQueueingDisciplinePriority;
    private javax.swing.JRadioButton rdbtnSincronizacionReceiveNonBlocking;
    private javax.swing.JRadioButton rdbtnSincronizacionReceiveTestForArrival;
    private javax.swing.JRadioButton rdbtnSincronizacionSendBlocking;
    private javax.swing.JRadioButton rdbtnSincronizacionSendNonBlocking;
    private javax.swing.JTextField txfProcessName;
    private javax.swing.JTextField txfProcessName1;
    // End of variables declaration//GEN-END:variables
}
